---
- name: Installing WordPress with Docker
  host: all
  remote_user: root
  tasks:
    - name: copy docker-compose.yml
      copy:
        src: app/
        dest: tmp/
        
    - name: test docker-compose
      docker_compose:
        project_src: tmp/
        state: present
  
