---
- name: Gathering facts
  hosts: webservers
  tasks:
    - name: print the facts
      debug:
        msg: "{{ ansible_hostname }}"
    - name: print the next facts
      debug:
        msg: "{{ ansible_os_family }}"
